/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3139.0) */

#include "ble_clock.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside CLOCK packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside CLOCK packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_HOURS_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted HOURS. */ 
#define MAX_MINUTES_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted MINUTES. */ 
#define MAX_SECONDS_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted SECONDS. */ 

/**@brief Function for encoding HOURS.
 *
 * @param[in]   p_hours              HOURS characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t hours_encode(ble_clock_hours_t * p_hours, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    encoded_buffer[len++] = p_hours->hours;
    return len;
}

/**@brief Function for decoding HOURS.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t hours_decode(uint8_t data_len, uint8_t * p_data, ble_clock_hours_t * p_write_val)
{
    uint8_t pos = 0;
    p_write_val->hours = p_data[pos++]; 

    return pos;
} 
/**@brief Function for encoding MINUTES.
 *
 * @param[in]   p_minutes              MINUTES characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t minutes_encode(ble_clock_minutes_t * p_minutes, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    encoded_buffer[len++] = p_minutes->minutes;
    return len;
}

/**@brief Function for decoding MINUTES.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t minutes_decode(uint8_t data_len, uint8_t * p_data, ble_clock_minutes_t * p_write_val)
{
    uint8_t pos = 0;
    p_write_val->minutes = p_data[pos++]; 

    return pos;
} 
/**@brief Function for encoding SECONDS.
 *
 * @param[in]   p_seconds              SECONDS characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t seconds_encode(ble_clock_seconds_t * p_seconds, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    encoded_buffer[len++] = p_seconds->seconds;
    return len;
}

/**@brief Function for decoding SECONDS.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t seconds_decode(uint8_t data_len, uint8_t * p_data, ble_clock_seconds_t * p_write_val)
{
    uint8_t pos = 0;
    p_write_val->seconds = p_data[pos++]; 

    return pos;
} 

/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_clock       CLOCK Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_clock_t * p_clock, ble_evt_t * p_ble_evt)
{
    p_clock->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_clock       CLOCK Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_clock_t * p_clock, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_clock->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_clock       CLOCK Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_clock_t * p_clock, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_clock->hours_handles.value_handle)
    {
        if(p_clock->evt_handler != NULL)
        {
            ble_clock_evt_t evt;
            evt.evt_type = BLE_CLOCK_HOURS_EVT_WRITE;
            hours_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.hours);
            p_clock->evt_handler(p_clock, &evt);
        }
    }
    if(p_ble_evt->handle == p_clock->minutes_handles.value_handle)
    {
        if(p_clock->evt_handler != NULL)
        {
            ble_clock_evt_t evt;
            evt.evt_type = BLE_CLOCK_MINUTES_EVT_WRITE;
            minutes_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.minutes);
            p_clock->evt_handler(p_clock, &evt);
        }
    }
    if(p_ble_evt->handle == p_clock->seconds_handles.value_handle)
    {
        if(p_clock->evt_handler != NULL)
        {
            ble_clock_evt_t evt;
            evt.evt_type = BLE_CLOCK_SECONDS_EVT_WRITE;
            seconds_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.seconds);
            p_clock->evt_handler(p_clock, &evt);
        }
    }
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_clock_t * p_clock, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
            if (p_auth_req->request.write.handle == p_clock->hours_handles.value_handle)
            {
                on_write(p_clock, &p_auth_req->request.write);
            }
            if (p_auth_req->request.write.handle == p_clock->minutes_handles.value_handle)
            {
                on_write(p_clock, &p_auth_req->request.write);
            }
            if (p_auth_req->request.write.handle == p_clock->seconds_handles.value_handle)
            {
                on_write(p_clock, &p_auth_req->request.write);
            }
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_clock       CLOCK Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_clock_on_ble_evt(ble_clock_t * p_clock, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_clock, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_clock, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_clock, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_clock, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the CLOCK. */
uint32_t ble_clock_init(ble_clock_t * p_clock, const ble_clock_init_t * p_clock_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_clock->evt_handler = p_clock_init->evt_handler;
    p_clock->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    // Add a custom base UUID.
    ble_uuid128_t bds_base_uuid = {{0x7E, 0x3D, 0x34, 0xFB, 0x87, 0x3D, 0x5E, 0x9F, 0x94, 0x44, 0x9E, 0xE6, 0x00, 0x00, 0x2A, 0x4B}};
    uint8_t       uuid_type;
    err_code = sd_ble_uuid_vs_add(&bds_base_uuid, &uuid_type);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    }
    ble_uuid.type = uuid_type;
    ble_uuid.uuid = 0x374F;
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_clock->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add HOURS characteristic
    ble_clock_hours_t hours_initial_value = p_clock_init->ble_clock_hours_initial_value; 

    uint8_t hours_encoded_value[MAX_HOURS_LEN];
    ble_add_char_params_t add_hours_params;
    memset(&add_hours_params, 0, sizeof(add_hours_params));
    
    add_hours_params.uuid                = 0x8EFF;
    add_hours_params.uuid_type           = ble_uuid.type; 
    add_hours_params.max_len             = MAX_HOURS_LEN;
    add_hours_params.init_len            = hours_encode(&hours_initial_value, hours_encoded_value);
    add_hours_params.p_init_value        = hours_encoded_value; 
    add_hours_params.char_props.read     = 1; 
    add_hours_params.read_access         = SEC_OPEN; 
    add_hours_params.char_props.write    = 1; 
    add_hours_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_hours_params.is_var_len          = 1; 

    err_code = characteristic_add(p_clock->service_handle, &add_hours_params, &(p_clock->hours_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add MINUTES characteristic
    ble_clock_minutes_t minutes_initial_value = p_clock_init->ble_clock_minutes_initial_value; 

    uint8_t minutes_encoded_value[MAX_MINUTES_LEN];
    ble_add_char_params_t add_minutes_params;
    memset(&add_minutes_params, 0, sizeof(add_minutes_params));
    
    add_minutes_params.uuid                = 0xB366;
    add_minutes_params.uuid_type           = ble_uuid.type; 
    add_minutes_params.max_len             = MAX_MINUTES_LEN;
    add_minutes_params.init_len            = minutes_encode(&minutes_initial_value, minutes_encoded_value);
    add_minutes_params.p_init_value        = minutes_encoded_value; 
    add_minutes_params.char_props.read     = 1; 
    add_minutes_params.read_access         = SEC_OPEN; 
    add_minutes_params.char_props.write    = 1; 
    add_minutes_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_minutes_params.is_var_len          = 1; 

    err_code = characteristic_add(p_clock->service_handle, &add_minutes_params, &(p_clock->minutes_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add SECONDS characteristic
    ble_clock_seconds_t seconds_initial_value = p_clock_init->ble_clock_seconds_initial_value; 

    uint8_t seconds_encoded_value[MAX_SECONDS_LEN];
    ble_add_char_params_t add_seconds_params;
    memset(&add_seconds_params, 0, sizeof(add_seconds_params));
    
    add_seconds_params.uuid                = 0x0428;
    add_seconds_params.uuid_type           = ble_uuid.type; 
    add_seconds_params.max_len             = MAX_SECONDS_LEN;
    add_seconds_params.init_len            = seconds_encode(&seconds_initial_value, seconds_encoded_value);
    add_seconds_params.p_init_value        = seconds_encoded_value; 
    add_seconds_params.char_props.read     = 1; 
    add_seconds_params.read_access         = SEC_OPEN; 
    add_seconds_params.char_props.write    = 1; 
    add_seconds_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_seconds_params.is_var_len          = 1; 

    err_code = characteristic_add(p_clock->service_handle, &add_seconds_params, &(p_clock->seconds_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for setting the HOURS. */
uint32_t ble_clock_hours_set(ble_clock_t * p_clock, ble_clock_hours_t * p_hours)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_HOURS_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = hours_encode(p_hours, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_clock->conn_handle, p_clock->hours_handles.value_handle, &gatts_value);
}

/**@brief Function for setting the MINUTES. */
uint32_t ble_clock_minutes_set(ble_clock_t * p_clock, ble_clock_minutes_t * p_minutes)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_MINUTES_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = minutes_encode(p_minutes, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_clock->conn_handle, p_clock->minutes_handles.value_handle, &gatts_value);
}

/**@brief Function for setting the SECONDS. */
uint32_t ble_clock_seconds_set(ble_clock_t * p_clock, ble_clock_seconds_t * p_seconds)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_SECONDS_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = seconds_encode(p_seconds, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_clock->conn_handle, p_clock->seconds_handles.value_handle, &gatts_value);
}

