/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3139.0) */

#include "ble_meter.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside METER packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside METER packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_HOT_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted HOT. */ 
#define MAX_COLD_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted COLD. */ 

/**@brief Function for encoding HOT.
 *
 * @param[in]   p_hot              HOT characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t hot_encode(ble_meter_hot_t * p_hot, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint32_encode(&p_hot->hot, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for decoding HOT.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t hot_decode(uint8_t data_len, uint8_t * p_data, ble_meter_hot_t * p_write_val)
{
    uint8_t pos = 0;
    pos += bds_uint32_decode((data_len-pos), &p_data[pos], &p_write_val->hot); 

    return pos;
} 
/**@brief Function for encoding COLD.
 *
 * @param[in]   p_cold              COLD characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t cold_encode(ble_meter_cold_t * p_cold, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint32_encode(&p_cold->cold, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for decoding COLD.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t cold_decode(uint8_t data_len, uint8_t * p_data, ble_meter_cold_t * p_write_val)
{
    uint8_t pos = 0;
    pos += bds_uint32_decode((data_len-pos), &p_data[pos], &p_write_val->cold); 

    return pos;
} 

/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_meter       METER Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_meter_t * p_meter, ble_evt_t * p_ble_evt)
{
    p_meter->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_meter       METER Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_meter_t * p_meter, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_meter->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_meter       METER Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_meter_t * p_meter, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_meter->hot_handles.cccd_handle)
    {
        if(p_meter->evt_handler != NULL)
        {
            ble_meter_evt_t evt;
            evt.evt_type = BLE_METER_HOT_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_meter->evt_handler(p_meter, &evt);
        }
    } 
    if(p_ble_evt->handle == p_meter->hot_handles.value_handle)
    {
        if(p_meter->evt_handler != NULL)
        {
            ble_meter_evt_t evt;
            evt.evt_type = BLE_METER_HOT_EVT_WRITE;
            hot_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.hot);
            p_meter->evt_handler(p_meter, &evt);
        }
    }
    if(p_ble_evt->handle == p_meter->cold_handles.cccd_handle)
    {
        if(p_meter->evt_handler != NULL)
        {
            ble_meter_evt_t evt;
            evt.evt_type = BLE_METER_COLD_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_meter->evt_handler(p_meter, &evt);
        }
    } 
    if(p_ble_evt->handle == p_meter->cold_handles.value_handle)
    {
        if(p_meter->evt_handler != NULL)
        {
            ble_meter_evt_t evt;
            evt.evt_type = BLE_METER_COLD_EVT_WRITE;
            cold_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cold);
            p_meter->evt_handler(p_meter, &evt);
        }
    }
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_meter_t * p_meter, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
            if (p_auth_req->request.write.handle == p_meter->hot_handles.value_handle)
            {
                on_write(p_meter, &p_auth_req->request.write);
            }
            if (p_auth_req->request.write.handle == p_meter->cold_handles.value_handle)
            {
                on_write(p_meter, &p_auth_req->request.write);
            }
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_meter       METER Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_meter_on_ble_evt(ble_meter_t * p_meter, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_meter, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_meter, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_meter, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_meter, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the METER. */
uint32_t ble_meter_init(ble_meter_t * p_meter, const ble_meter_init_t * p_meter_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_meter->evt_handler = p_meter_init->evt_handler;
    p_meter->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    // Add a custom base UUID.
    ble_uuid128_t bds_base_uuid = {{0x7E, 0x3D, 0x34, 0xFB, 0x87, 0x3D, 0x5E, 0x9F, 0x94, 0x44, 0x9E, 0xE6, 0x00, 0x00, 0x2A, 0x4B}};
    uint8_t       uuid_type;
    err_code = sd_ble_uuid_vs_add(&bds_base_uuid, &uuid_type);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    }
    ble_uuid.type = uuid_type;
    ble_uuid.uuid = 0x25DF;
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_meter->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add HOT characteristic
    ble_meter_hot_t hot_initial_value = p_meter_init->ble_meter_hot_initial_value; 

    uint8_t hot_encoded_value[MAX_HOT_LEN];
    ble_add_char_params_t add_hot_params;
    memset(&add_hot_params, 0, sizeof(add_hot_params));
    
    add_hot_params.uuid                = 0x9C41;
    add_hot_params.uuid_type           = ble_uuid.type; 
    add_hot_params.max_len             = MAX_HOT_LEN;
    add_hot_params.init_len            = hot_encode(&hot_initial_value, hot_encoded_value);
    add_hot_params.p_init_value        = hot_encoded_value; 
    add_hot_params.char_props.notify   = 1; 
    add_hot_params.char_props.indicate = 1; 
    add_hot_params.char_props.read     = 1; 
    add_hot_params.read_access         = SEC_OPEN; 
    add_hot_params.char_props.write    = 1; 
    add_hot_params.write_access        = SEC_OPEN; 
    add_hot_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_hot_params.is_var_len          = 1; 

    err_code = characteristic_add(p_meter->service_handle, &add_hot_params, &(p_meter->hot_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add COLD characteristic
    ble_meter_cold_t cold_initial_value = p_meter_init->ble_meter_cold_initial_value; 

    uint8_t cold_encoded_value[MAX_COLD_LEN];
    ble_add_char_params_t add_cold_params;
    memset(&add_cold_params, 0, sizeof(add_cold_params));
    
    add_cold_params.uuid                = 0xFC42;
    add_cold_params.uuid_type           = ble_uuid.type; 
    add_cold_params.max_len             = MAX_COLD_LEN;
    add_cold_params.init_len            = cold_encode(&cold_initial_value, cold_encoded_value);
    add_cold_params.p_init_value        = cold_encoded_value; 
    add_cold_params.char_props.notify   = 1; 
    add_cold_params.char_props.indicate = 1; 
    add_cold_params.char_props.read     = 1; 
    add_cold_params.read_access         = SEC_OPEN; 
    add_cold_params.char_props.write    = 1; 
    add_cold_params.write_access        = SEC_OPEN; 
    add_cold_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_cold_params.is_var_len          = 1; 

    err_code = characteristic_add(p_meter->service_handle, &add_cold_params, &(p_meter->cold_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for setting the HOT. */
uint32_t ble_meter_hot_set(ble_meter_t * p_meter, ble_meter_hot_t * p_hot)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_HOT_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = hot_encode(p_hot, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_meter->conn_handle, p_meter->hot_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the HOT. */
uint32_t ble_meter_hot_notify(ble_meter_t * p_meter, ble_meter_hot_t * p_hot)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_meter->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_HOT_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = hot_encode(p_hot, encoded_value);
        hvx_params.handle = p_meter->hot_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_meter->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

/**@brief Function for sending the HOT. */
uint32_t ble_meter_hot_indicate(ble_meter_t * p_meter, ble_meter_hot_t * p_hot)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_meter->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_HOT_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = hot_encode(p_hot, encoded_value);
        hvx_params.handle = p_meter->hot_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_INDICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_meter->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

/**@brief Function for setting the COLD. */
uint32_t ble_meter_cold_set(ble_meter_t * p_meter, ble_meter_cold_t * p_cold)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_COLD_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = cold_encode(p_cold, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_meter->conn_handle, p_meter->cold_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the COLD. */
uint32_t ble_meter_cold_notify(ble_meter_t * p_meter, ble_meter_cold_t * p_cold)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_meter->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_COLD_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = cold_encode(p_cold, encoded_value);
        hvx_params.handle = p_meter->cold_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_meter->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

/**@brief Function for sending the COLD. */
uint32_t ble_meter_cold_indicate(ble_meter_t * p_meter, ble_meter_cold_t * p_cold)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_meter->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_COLD_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = cold_encode(p_cold, encoded_value);
        hvx_params.handle = p_meter->cold_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_INDICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_meter->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

